Reformatting and migrate raster to terra
GeoScripting-WUR/IntroToRaster pull request #15
Opened 2022-11-28 15:39 UTC by mvansluijs

@GreatEmerald Please also take a look at the overview image. I got a bit lost in what currently binds to what, but I believe this is correct. Please correct me if I am wrong. If the image is OK, I'll also update the course guide image.

2022-12-01 18:01 UTC, GreatEmerald commented
For the flowchart:
1. Reading the [manual](https://pypi.org/project/GDAL/), it seems that "osgeo" is not an actual package, it's just a global name for imports, and [OGR is just a part of GDAL](https://trac.osgeo.org/gdal/wiki/FAQGeneral). So we can simplify the graph further by removing "osgeo" (or replacing it with "gdal") and "OGR".
2. I prefer using logos that include text, even if it's Python. Not everyone is familiar with its logo.
3. The list of R GUIs is intentional. RStudio is not the only GUI that can be used. It's also open-core software and in fact a web browser. RKWard is fully open-source, much more light-weight and often more stable.
4. There should be an arrow going from GDAL to output, because it's ultimately GDAL that reads and writes the data. Core Python and R only read CSV data.
5. We should take into account Google Earth Engine too. The IDE is the web browser, the engine is Google Earth Engine, it has no packages nor libraries, but it has a binding to Python called [earthengine-api or ee](https://developers.google.com/earth-engine/guides/python_install). It stores its scripts in git, and the data in cloud storage (Google Drive or Google Cloud Storage); it's useful to add that in parallel with git as a place to store data, because data should not actually go to git.

2022-12-01 19:12 UTC, GreatEmerald requested changes
Some suggestions:

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +**Tip**: Check the [home page](http://cran.r-project.org/web/packages/terra/) of the *terra* package. The package is extremely well documented, including vignettes and demos. See also the [reference
It's useful to mention this terra reference: https://rspatial.org/spatial/index.html

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +The terra package produces and uses R objects of two main classes. **SpatRaster** and **SpatVector**. A SpatRaster represents a spatially referenced surface divided into three dimensional cells (rows
```suggestion
The terra package produces and uses R objects of two main classes: **SpatRaster** and **SpatVector**. A SpatRaster represents a spatially referenced surface divided into three dimensional cells (rows, columns, and layers). A SpatVector represents geometries as well as attributes (variables) describing the geometries. Note: we will be using *terra* only for raster processing, as you will see in subsequent tutorials.
```

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +From the metadata displayed above, we can see that the SpatRaster contains all the properties that geo-data should have; that is to say a projection, an extent and a pixel resolution.
Technically:
```suggestion
From the metadata displayed above, we can see that the SpatRaster contains all the properties that geo-data should have; that is to say a coordinate reference system, an extent and a pixel size.
```

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +*Gewata* is the name of the data set added. It is a multi-layer GeoTIFF object, and its file name is *LE71700552001036SGS00\_SR\_Gewata\_INT1U.tif*, informing us that this is a subset from a scene ac
```suggestion
*Gewata* is the name of the dataset that we just downloaded. It is a multi-layer GeoTIFF object, and its file name is *LE71700552001036SGS00\_SR\_Gewata\_INT1U.tif*, informing us that this is a subset from a scene acquired by the Landsat 7 ETM+ sensor. Let's not worry about the region that the data covers for now, we will find a nice way to discover that later on in the tutorial.
```

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +`crop()` is the terra package function that allows you to crop data to smaller spatial extents. A great advantage of the crop function is that it accepts almost all spatial object classes in R as its
The function doesn't have an `extent` input argument any more. The `y` argument accepts `SpatExtent`, not `extent`.

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +Now you have to define a rectangular bounding box that will define the spatial extent of the extent object. Click twice, for the two opposite corners of the rectangle. Now we can crop the data follow
It may be good to add a note here that R will wait until you finish drawing before it will let you run any more code. A lot of students think that their R crashes or is very slow when they do draw(), but it's just waiting for them to finish drawing. (I remember a case where a student said "I'm waiting for R to run my code!", to which I replied "and R is waiting for you to draw an extent!" :) )

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +To end this section on general files and raster object manipulations, we will see more in-depth how multi-layer objects can be created from single-layer objects. The object created as part of the exa
Hmm, do we actually use the tura dataset anywhere else in the course, as this paragraph states? I don't remember that...

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +writeRaster(x = turaStack, filename = 'output/turaStack.tif', names = list.files(path = 'data/tura/'), datatype = "INT2S")
Alternatively `names = basename(list)`

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +Performing simple raster operations with a SpatRaster is fairly easy. For instance, if you want to subtract two SpatRasters of same extent, `r1` and `r2`; simply doing `r1 - r2` will give the expecte
```suggestion
Performing simple raster operations with a SpatRaster is fairly easy. For instance, if you want to subtract two SpatRasters of same extent, `r1` and `r2`; simply doing `r1 - r2` will give the expected output, which is, every pixel value of `r2` will be subtracted from the matching pixel value of `r1`. These types of pixel-based operations almost always require a set of conditions to be met in order to be executed; the two SpatRasters need to be identical in term of extent, pixel size, coordinate reference system, etc.
```

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +Different spectral bands of a same satellite scene are often stored in multi-layer objects. This means that you will very likely import them in your R working environment as one multi-layer SpatRaste
```suggestion
Different spectral bands of the same satellite scene are often stored in multi-layer objects. This means that you will very likely import them in your R working environment as one multi-layer SpatRaster. As a consequence, to perform calculations between these bands, you will have to write an expression referring to individual layers of the object. Referring to individual layers in a SpatRaster can be done by using double square brackets `[[]]`.
```

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +The `project()` function allows re-projection of raster objects to any projection one can think of. It accepts the following formats to define coordinate reference systems: *WKT*, *PROJ.4* (e.g., +pr
```suggestion
The `project()` function allows re-projection of raster objects to any projection one can think of. It accepts the following formats to define coordinate reference systems: *WKT*, *PROJ.4* (e.g., `+proj=longlat +datum=WGS84`), or an *EPSG* code (e.g., `epsg:4326`). Note that the PROJ.4 notation has been deprecated, and you can only use it with the WGS84/NAD83 and NAD27 datums. Other datums are silently ignored.
```

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +A central place to search for projections is the spatial reference website ([http://spatialreference.org/](http://spatialreference.org/)), from this database you will be able to query almost any refe
```suggestion
A central place to search for coordinate reference systems is the spatial reference website ([http://spatialreference.org/](http://spatialreference.org/)), from this database you will be able to query almost any reference and retrieve it in any format, including its *EPSG* code. Well-Known Text (*WKT*) expressions are preferred for scientific correctness and lack of ambiguity.
```

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +Instead of specifying a projection to convert to, you can also provide `project()` with another SpatRaster, and it will convert your input to the projection of that SpatRaster.
```suggestion
Instead of specifying a coordinate reference system to convert to, you can also provide `project()` with another SpatRaster, and it will convert your input to the CRS of that SpatRaster.
```

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +# One single line is sufficient to project any raster to any projection
```suggestion
# One single line is sufficient to project any raster to any CRS
```

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +ndviLL <- project(ndvi, '+proj=longlat')
We should probably encourage using EPSG codes instead of the deprecated proj.4.

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +By the way, we still don't know where this area is. In order to investigate that, we are going to try projecting it in QGIS. Let's write our NDVI layer in Lat/Long to a .tif file first.
```suggestion
By the way, we still don't know where this area is. In order to investigate that, we are going to try displaying it in QGIS. Let's write our NDVI layer in Lat/Long to a .tif file first.
```

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +Now open this file in QGIS (or ArcGIS), and add a base layer (in QGIS for instance OpenStreetMap, using XYZ tiles with the url `https://tile.openstreetmap.org/{z}/{x}/{y}.png`). Once we zoom out a bi
Not in ArcGIS, as it does not run in Linux, and that's what we are using in the course.

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +tahitiCloudFree <- app(x = c(tahiti6_2, fmask), fun = cloud2NA)
With `app()` this is actually much simpler: `c(tahiti6_2, fmask)` is simply `tahiti`. So we can skip line 417 altogether.

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +* `SpatVector`: Geometries object (vector).
```suggestion
* `SpatRaster`: Single- or multi-layer raster object.
* `SpatVector`: Vector object.
```

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> +* `crop()`: modify the extent of a `SpatRaster` based on another spatial object or an extent object.
```suggestion
* `crop()`: modify the extent of a `SpatRaster` based on another spatial object or a `SpatExtent` object.
```

2022-12-01 19:12 UTC, GreatEmerald commented on index.Rmd
> -* `stack()`: Assemble RasterLayers in a multi-layer object.
You should mention the use of `c()` in that case.

2022-12-02 13:35 UTC, mvansluijs commented on index.Rmd
> +To end this section on general files and raster object manipulations, we will see more in-depth how multi-layer objects can be created from single-layer objects. The object created as part of the exa
No, it used to be in the course, it's now in Demo 2: https://geoscripting-wur.github.io/Scripting4Geo/#Demo_2__Visualize_the_temporal_profile_of_a_pixel. I'll remove the reference from this text.

2022-12-02 13:58 UTC, mvansluijs commented on index.Rmd
> +writeRaster(x = turaStack, filename = 'output/turaStack.tif', names = list.files(path = 'data/tura/'), datatype = "INT2S")
We use list.files() in 205 as well, which also seems more intuïtive tbh

2022-12-02 14:19 UTC, mvansluijs commented
@GreatEmerald I still have to take a closer look at the flowchart, but might not be able to finish that today. The rest of the suggestions should be implemented now.

2022-12-02 14:32 UTC, GreatEmerald commented on index.Rmd
> +writeRaster(x = turaStack, filename = 'output/turaStack.tif', names = list.files(path = 'data/tura/'), datatype = "INT2S")
Yes, it's just a bit odd that the `list` object is then not so useful :) But it's not a big deal.

2022-12-02 14:50 UTC, GreatEmerald requested changes
Still a couple of points:

2022-12-02 14:50 UTC, GreatEmerald commented on index.Rmd
> +ndviLL <- project(ndvi, 'epsg:28992')
The "LL" I think stands for Long Lat, but 28992 is RD New. I think we are supposed to use WGS84 here?

2022-12-02 14:50 UTC, GreatEmerald commented on index.Rmd
> +* `c()`: Combina multiple SpatRasters into a single SpatRaster.
```suggestion
* `c()`: Combine multiple SpatRasters into a single SpatRaster.
```

2022-12-04 11:49 UTC, mvansluijs commented
@GreatEmerald Two points implemented; also made updates to the overview image. Let me know what you think.

2022-12-05 14:07 UTC, GreatEmerald requested changes
Thanks, looks much improved, just a few more suggestions for the graph:
1. `earthengine-api` is technically both a package and a binding, so it can be put a bit higher, at the same height as pyproj.
2. The flow technically is reversed: Python should point to earthengine-api, which should then point to Earth Engine, as it's a way for Python to access Earth Engine and not the other way round.
3. There should be a space in "Web browser"
4. Don't forget to also add an updated .odg file, if that's the one you updated

2022-12-05 15:14 UTC, mvansluijs commented
@GreatEmerald suggestions 1, 2 and 3 are now implemented. I do not have a .odg file, as I edited the .svg file directly, which means I cannot provide suggestion 4.

Also, I just found out I can simply (pre)view the my fork directly online as it is hosted through https://mvansluijs.github.io/IntroToRaster/ !

2022-12-05 15:30 UTC, GreatEmerald approved these changes
Hah, a bit late, but good to know that it happens automatically :) Thanks!

2022-12-05 15:30 UTC, merged